framework:
  assets:
    packages:
      front_build:
        json_manifest_path: '%kernel.project_dir%/public/front/manifest.json'
      admin_build:
        json_manifest_path: '%kernel.project_dir%/public/admin/manifest.json'